### ISSUE TITLE
TWexe does not work with Tiddlywiki 5.1.23

### ISSUE THREAD

**Issue by kookma** [ihm4u/twexe#5]
Thank you for this awesome app!

Would you please update twexe to support tw 5.1.23+

**Comment by arteteco** [comment]
Hi,
do you mean 5.1.13+? I think TW didn't reach 5.2.x yet, last release is 5.1.23

Also, what do you mean it doesn't support it? I just downloaded a 5.1.23 and `twexe empty.html`, worked without issues

**Comment by kookma** [comment]
Hi @arteteco 
Yes, my bad, it is TW 5.1.23! The issue title is correct!

And thank you for your note! I redownloaded the **twexe** and it works like a charm even with Tiddlywiki 5.1.24pre.

Thank you!
